from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1084, 467)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(660, 40, 411, 201))
        self.textEdit.setObjectName("textEdit")
        self.privateKeysList = QtWidgets.QListWidget(self.centralwidget)
        self.privateKeysList.setGeometry(QtCore.QRect(10, 40, 256, 192))
        self.privateKeysList.setObjectName("privateKeysList")
        self.publicKeyList = QtWidgets.QListWidget(self.centralwidget)
        self.publicKeyList.setGeometry(QtCore.QRect(290, 40, 271, 192))
        self.publicKeyList.setObjectName("publicKeyList")
        self.sendFromCombo = QtWidgets.QComboBox(self.centralwidget)
        self.sendFromCombo.setGeometry(QtCore.QRect(10, 250, 170, 22))
        self.sendFromCombo.setObjectName("sendFromCombo")
        self.sentToCombo = QtWidgets.QComboBox(self.centralwidget)
        self.sentToCombo.setGeometry(QtCore.QRect(290, 250, 170, 22))
        self.sentToCombo.setObjectName("sentToCombo")
        self.compressCheckbox = QtWidgets.QCheckBox(self.centralwidget)
        self.compressCheckbox.setGeometry(QtCore.QRect(10, 330, 101, 20))
        self.compressCheckbox.setObjectName("compressCheckbox")
        self.aesRadioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.aesRadioButton.setGeometry(QtCore.QRect(150, 370, 95, 20))
        self.aesRadioButton.setObjectName("aesRadioButton")
        self.tripleDESRadioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.tripleDESRadioButton.setGeometry(QtCore.QRect(260, 370, 95, 20))
        self.tripleDESRadioButton.setObjectName("tripleDESRadioButton")
        self.sendMessageButton = QtWidgets.QPushButton(self.centralwidget)
        self.sendMessageButton.setGeometry(QtCore.QRect(660, 260, 93, 28))
        self.sendMessageButton.setObjectName("sendMessageButton")
        self.receiveMessageButton = QtWidgets.QPushButton(self.centralwidget)
        self.receiveMessageButton.setGeometry(QtCore.QRect(770, 260, 93, 28))
        self.receiveMessageButton.setObjectName("receiveMessageButton")
        self.importKeyButton = QtWidgets.QPushButton(self.centralwidget)
        self.importKeyButton.setGeometry(QtCore.QRect(470, 250, 93, 28))
        self.importKeyButton.setObjectName("importKeyButton")
        self.exportKeyButton = QtWidgets.QPushButton(self.centralwidget)
        self.exportKeyButton.setGeometry(QtCore.QRect(470, 290, 93, 28))
        self.exportKeyButton.setObjectName("exportKeyButton")
        self.symAlgoLabel = QtWidgets.QLabel(self.centralwidget)
        self.symAlgoLabel.setGeometry(QtCore.QRect(10, 370, 131, 16))
        self.symAlgoLabel.setObjectName("symAlgoLabel")
        self.privateKeysLabel = QtWidgets.QLabel(self.centralwidget)
        self.privateKeysLabel.setGeometry(QtCore.QRect(10, 20, 91, 16))
        self.privateKeysLabel.setObjectName("privateKeysLabel")
        self.publicKeysLabel = QtWidgets.QLabel(self.centralwidget)
        self.publicKeysLabel.setGeometry(QtCore.QRect(290, 20, 81, 16))
        self.publicKeysLabel.setObjectName("publicKeysLabel")
        self.messageLabel = QtWidgets.QLabel(self.centralwidget)
        self.messageLabel.setGeometry(QtCore.QRect(660, 20, 71, 16))
        self.messageLabel.setObjectName("messageLabel")
        self.generateKeyButton = QtWidgets.QPushButton(self.centralwidget)
        self.generateKeyButton.setGeometry(QtCore.QRect(470, 330, 93, 28))
        self.generateKeyButton.setObjectName("generateKeyButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PGP local simulator"))
        self.compressCheckbox.setText(_translate("MainWindow", "Compressed"))
        self.aesRadioButton.setText(_translate("MainWindow", "AES128"))
        self.tripleDESRadioButton.setText(_translate("MainWindow", "TripleDES"))
        self.sendMessageButton.setText(_translate("MainWindow", "Send"))
        self.receiveMessageButton.setText(_translate("MainWindow", "Receive"))
        self.importKeyButton.setText(_translate("MainWindow", "Import Key"))
        self.exportKeyButton.setText(_translate("MainWindow", "Export Key"))
        self.symAlgoLabel.setText(_translate("MainWindow", "Symmetric algorithm:"))
        self.privateKeysLabel.setText(_translate("MainWindow", "Private keys:"))
        self.publicKeysLabel.setText(_translate("MainWindow", "Public keys:"))
        self.messageLabel.setText(_translate("MainWindow", "Message:"))
        self.generateKeyButton.setText(_translate("MainWindow", "Generate Keys"))